name: ci

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome lint --error-on-warnings --skip=lint/suspicious/noAssignInExpressions --skip lint/suspicious/noDocumentCookie --skip lint/suspicious/useIterableCallbackReturn --skip lint/suspicious/noRedundantUseStrict .
